name: Puppeteer Cronjob

on:
  push:
  schedule:
    - cron: '*/6 * * * *' 
  workflow_dispatch: 

jobs:
  run-puppeteer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        run: npm start
